In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [68]:
df = pd.read_csv('tobacco.csv')

In [5]:
df.head(15)

,Year,State,Smoke everyday,Smoke some days,Former smoker,Never smoked,Location 1
0,1996,Puerto Rico,9.40%,5.10%,16%,69.50%,Puerto Rico\n
1,1997,Puerto Rico,9.40%,5%,15.70%,69.90%,Puerto Rico\n
2,1998,Puerto Rico,10.10%,5.20%,16.80%,67.90%,Puerto Rico\n
3,1999,Puerto Rico,9.70%,4%,15.30%,71%,Puerto Rico\n
4,2000,Puerto Rico,9.20%,3.90%,15.20%,71.60%,Puerto Rico\n
5,2001,Puerto Rico,8%,4.50%,17%,70.50%,Puerto Rico\n
6,2001,Virgin Islands,6.90%,2.70%,12.60%,77.80%,Virgin Islands\n
7,2002,Puerto Rico,8.80%,4.40%,16.90%,69.80%,Puerto Rico\n
8,2002,Virgin Islands,7%,2.40%,12.10%,78.50%,Virgin Islands\n
9,2003,Puerto Rico,8.90%,4.60%,17.70%,68.80%,Puerto Rico\n
10,2003,Virgin Islands,7.90%,2%,13.60%,76.40%,Virgin Islands\n
11,2004,Puerto Rico,8.20%,4.40%,15.20%,72.20%,Puerto Rico\n
12,2004,Virgin Islands,5.90%,3.50%,9.90%,80.70%,Virgin Islands\n
13,2005,Puerto Rico,7.90%,5.20%,16.90%,70%,Puerto Rico\n
14,2005,Virgin Islands,5.30%,2.80%,12.80%,79.10%,Virgin Islands\n

In [22]:
ny = df.loc[df.State=='New York']

In [31]:
ny = ny.sort_values(by='Year').reset_index(drop=True)

In [37]:
def get_state(state):
    return df.loc[df.State==state].sort_values(by='Year').reset_index(drop=True)

In [42]:
az = get_state('Arizona')
ca = get_state('California')
ut = get_state('Utah')
wa = get_state('Washington')
wv = get_state('West Virginia')
ky = get_state('Kentucky')
tx = get_state('Texas')

In [43]:
tx

,Year,State,Smoke everyday,Smoke some days,Former smoker,Never smoked,Location 1
0,1995,Texas,19.90%,3.60%,23.70%,52.80%,"Texas\n(31.82724000022597, -99.42676999973554)"
1,1996,Texas,17%,5.90%,21.20%,55.90%,"Texas\n(31.82724000022597, -99.42676999973554)"
2,1997,Texas,16.20%,6.30%,20.30%,57.10%,"Texas\n(31.82724000022597, -99.42676999973554)"
3,1998,Texas,15.60%,6.30%,22.60%,55.50%,"Texas\n(31.82724000022597, -99.42676999973554)"
4,1999,Texas,15%,7.50%,23.30%,54.30%,"Texas\n(31.82724000022597, -99.42676999973554)"
5,2000,Texas,15.40%,6.50%,21.90%,56.20%,"Texas\n(31.82724000022597, -99.42676999973554)"
6,2001,Texas,15.50%,6.90%,20.70%,56.90%,"Texas\n(31.82724000022597, -99.42676999973554)"
7,2002,Texas,16.60%,6.20%,20.90%,56.20%,"Texas\n(31.82724000022597, -99.42676999973554)"
8,2003,Texas,15.60%,6.50%,21.60%,56.30%,"Texas\n(31.82724000022597, -99.42676999973554)"
9,2004,Texas,13.60%,6.90%,20.20%,59.30%,"Texas\n(31.82724000022597, -99.42676999973554)"
10,2005,Texas,13.20%,6.80%,21%,59%,"Texas\n(31.82724000022597, -99.42676999973554)"
11,2006,Texas,12.60%,5.30%,21.70%,60.40%,"Texas\n(31.82724000022597, -99.42676999973554)"
12,2007,Texas,13%,6.40%,20.70%,60%,"Texas\n(31.82724000022597, -99.42676999973554)"
13,2008,Texas,11.70%,6.80%,21.50%,60%,"Texas\n(31.82724000022597, -99.42676999973554)"
14,2009,Texas,11.70%,6.20%,21.60%,60.50%,"Texas\n(31.82724000022597, -99.42676999973554)"
15,2010,Texas,10.50%,5.30%,21.30%,62.90%,"Texas\n(31.82724000022597, -99.42676999973554)"

In [44]:
wv

,Year,State,Smoke everyday,Smoke some days,Former smoker,Never smoked,Location 1
0,1995,West Virginia,23.70%,1.90%,23.30%,51.10%,"West Virginia\n(38.66550999958696, -80.7126399..."
1,1996,West Virginia,23.90%,2.80%,22.90%,50.50%,"West Virginia\n(38.66550999958696, -80.7126399..."
2,1997,West Virginia,24.50%,2.90%,24.30%,48.20%,"West Virginia\n(38.66550999958696, -80.7126399..."
3,1998,West Virginia,24.90%,3.10%,23.80%,48.30%,"West Virginia\n(38.66550999958696, -80.7126399..."
4,1999,West Virginia,23.80%,3.30%,23.80%,49%,"West Virginia\n(38.66550999958696, -80.7126399..."
5,2000,West Virginia,23.10%,3%,25.30%,48.50%,"West Virginia\n(38.66550999958696, -80.7126399..."
6,2001,West Virginia,23.50%,4.60%,24.70%,47.10%,"West Virginia\n(38.66550999958696, -80.7126399..."
7,2002,West Virginia,23.80%,4.70%,24.20%,47.40%,"West Virginia\n(38.66550999958696, -80.7126399..."
8,2003,West Virginia,22.60%,4.80%,25.80%,46.90%,"West Virginia\n(38.66550999958696, -80.7126399..."
9,2004,West Virginia,21.80%,5.10%,25.10%,48%,"West Virginia\n(38.66550999958696, -80.7126399..."
10,2005,West Virginia,21.30%,5.40%,24.30%,49%,"West Virginia\n(38.66550999958696, -80.7126399..."
11,2006,West Virginia,21.30%,4.50%,24.70%,49.60%,"West Virginia\n(38.66550999958696, -80.7126399..."
12,2007,West Virginia,21.70%,5.20%,24.50%,48.60%,"West Virginia\n(38.66550999958696, -80.7126399..."
13,2008,West Virginia,21.50%,5.10%,25.40%,48.10%,"West Virginia\n(38.66550999958696, -80.7126399..."
14,2009,West Virginia,20.70%,4.90%,24.50%,49.90%,"West Virginia\n(38.66550999958696, -80.7126399..."
15,2010,West Virginia,23.20%,3.60%,24.40%,48.80%,"West Virginia\n(38.66550999958696, -80.7126399..."

In [45]:
ky

,Year,State,Smoke everyday,Smoke some days,Former smoker,Never smoked,Location 1
0,1995,Kentucky,24.90%,2.70%,22.30%,50.10%,"Kentucky\n(37.645969999815804, -84.77496999996..."
1,1996,Kentucky,27.90%,3.80%,23.20%,45.20%,"Kentucky\n(37.645969999815804, -84.77496999996..."
2,1997,Kentucky,27.60%,3.10%,23.50%,45.80%,"Kentucky\n(37.645969999815804, -84.77496999996..."
3,1998,Kentucky,28%,2.80%,22.90%,46.30%,"Kentucky\n(37.645969999815804, -84.77496999996..."
4,1999,Kentucky,25.60%,4.20%,23.20%,47.10%,"Kentucky\n(37.645969999815804, -84.77496999996..."
5,2000,Kentucky,26.80%,3.70%,23%,46.50%,"Kentucky\n(37.645969999815804, -84.77496999996..."
6,2001,Kentucky,26.20%,4.70%,23.60%,45.50%,"Kentucky\n(37.645969999815804, -84.77496999996..."
7,2002,Kentucky,29.10%,3.50%,22%,45.50%,"Kentucky\n(37.645969999815804, -84.77496999996..."
8,2003,Kentucky,26.80%,4%,22.50%,46.70%,"Kentucky\n(37.645969999815804, -84.77496999996..."
9,2004,Kentucky,23%,4.50%,20.40%,52.10%,"Kentucky\n(37.645969999815804, -84.77496999996..."
10,2005,Kentucky,23.50%,5.20%,24%,47.30%,"Kentucky\n(37.645969999815804, -84.77496999996..."
11,2006,Kentucky,24.30%,4.30%,24.30%,47.20%,"Kentucky\n(37.645969999815804, -84.77496999996..."
12,2007,Kentucky,23.50%,4.70%,23.90%,47.90%,"Kentucky\n(37.645969999815804, -84.77496999996..."
13,2008,Kentucky,20.50%,4.70%,25.30%,49.50%,"Kentucky\n(37.645969999815804, -84.77496999996..."
14,2009,Kentucky,20.60%,5%,25.30%,49.10%,"Kentucky\n(37.645969999815804, -84.77496999996..."
15,2010,Kentucky,19.30%,5.50%,26%,49.20%,"Kentucky\n(37.645969999815804, -84.77496999996..."

In [56]:
df.dtypes

Year                int64
State              object
Smoke everyday     object
Smoke some days    object
Former smoker      object
Never smoked       object
Location 1         object
dtype: object

In [69]:
df['Smoke everyday'] = np.array(list(map(lambda x: float(str(x)[:-1]), df['Smoke everyday'])))

In [70]:
df.head()

,Year,State,Smoke everyday,Smoke some days,Former smoker,Never smoked,Location 1
0,1996,Puerto Rico,9.4,5.10%,16%,69.50%,Puerto Rico\n
1,1997,Puerto Rico,9.4,5%,15.70%,69.90%,Puerto Rico\n
2,1998,Puerto Rico,10.1,5.20%,16.80%,67.90%,Puerto Rico\n
3,1999,Puerto Rico,9.7,4%,15.30%,71%,Puerto Rico\n
4,2000,Puerto Rico,9.2,3.90%,15.20%,71.60%,Puerto Rico\n

In [71]:
df.describe()

              Year  Smoke everyday
count   876.000000      876.000000
mean   2002.591324       16.555479
std       4.593622        3.981661
min    1995.000000        3.600000
25%    1999.000000       13.900000
50%    2003.000000       16.700000
75%    2007.000000       19.100000
max    2010.000000       29.100000